/* Bar functionality */
#include "bar_indicators.h"
#include "bar_tagicons.h"
#include "bar.h"

#include "bar_alpha.h"
#include "bar_dwmblocks.h"
#include "bar_ltsymbol.h"
#include "bar_status.h"
#include "bar_statuscmd.h"
#include "bar_tags.h"
#include "bar_wintitle.h"
#include "bar_awesomebar.h"
#include "bar_systray.h"
#include "bar_wintitleactions.h"

/* Other patches */
#include "alttab.h"
#include "attachx.h"
#include "cfacts.h"
#include "dragcfact.h"
#include "dragmfact.h"
#include "inplacerotate.h"
#include "restartsig.h"
#include "rotatestack.h"
#include "scratchpad.h"
#include "seamless_restart.h"
#include "stacker.h"
#include "sticky.h"
#include "swallow.h"
#include "vanitygaps.h"
#include "warp.h"
/* Layouts */
#include "layout_centeredmaster.h"
#include "layout_flextile-deluxe.h"
#include "layout_grid.h"
#include "layout_monocle.h"
#include "layout_tile.h"

